[package]
authors = ["Toshiki.Kawazoe <toshiki.kawazoe@sony.com>"]
edition = "2021"
name = "work_calc"
rust-version = "1.62.1"
version = "1.2.3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "3.2.16", features = ["yaml"]}
env_logger = "0.9.0"
log = "0.4.17"
serde = {version = "1.0.143", features = ["derive"]}
toml = "0.5.9"
