[package]
name = "work_calc"
version = "0.6.0"
authors = ["Toshiki.Kawazoe <toshiki.kawazoe@sony.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.4.3"
