[package]
authors = ["Toshiki.Kawazoe <toshiki.kawazoe@sony.com>"]
edition = "2018"
name = "work_calc"
version = "1.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "2.33.3", features = ["yaml"]}
env_logger = "0.8.4"
log = "0.4.14"
serde = {version = "1.0.130", features = ["derive"]}
toml = "0.5.8"
