[package]
name = "man_hour"
version = "0.3.1"
authors = ["Toshiki.Kawazoe <toshiki.kawazoe@sony.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.4.3"
