[general]
# 合計労働時間を指定
# 優先度は `オプション指定` > `設定ファイル` > `コンソール直接入力`
# total_hour = 140.0

# 労働日数を指定
# 優先度は `オプション指定` > `設定ファイル` > `コンソール直接入力`
# work_days = 18

# [[cases]]
# number = 案件番号
# percent = 割合を指定(全体で1になること)
# remark = メモなどを記入

[[cases]]
number = "999999-99"
percent = 0.5
remark = "メモなど"

[[cases]]
number = "111111-11"
percent = 0.5
remark = "メモとか"
